{{- if .Values.calendar.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calendar-chart.fullname" . }}-calendar
  labels:
    {{- include "calendar-chart.calendar.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.calendar.replicaCount }}
  selector:
    matchLabels:
      {{- include "calendar-chart.calendar.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "calendar-chart.calendar.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: calendar-api
        image: "{{ .Values.global.imageRegistry }}{{ .Values.calendar.image.repository }}:{{ .Values.calendar.image.tag }}"
        imagePullPolicy: {{ .Values.calendar.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.calendar.service.targetPort }}
          protocol: TCP
        env:
        - name: CONFIG_FILE
          value: "/etc/calendar/config.yaml"
        - name: DB_HOST
          value: {{ .Values.database.host | quote }}
        - name: DB_PORT
          value: {{ .Values.database.port | quote }}
        - name: DB_USER
          value: {{ .Values.database.user | quote }}
        - name: DB_NAME
          value: {{ .Values.database.dbname | quote }}
        - name: LOGGER_LEVEL
          value: {{ .Values.logger.level | quote }}
        volumeMounts:
        - name: config
          mountPath: /etc/calendar
          readOnly: true
        - name: migrations
          mountPath: /migrations
          readOnly: true
        {{- if .Values.calendar.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.calendar.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.calendar.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.calendar.readinessProbe | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.calendar.resources | nindent 10 }}
      volumes:
      - name: config
        configMap:
          name: {{ include "calendar-chart.fullname" . }}-calendar-config
      - name: migrations
        configMap:
          name: {{ include "calendar-chart.fullname" . }}-migrations
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

