{{- if and .Values.calendar.enabled .Values.calendar.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "calendar-chart.fullname" . }}-calendar
  labels:
    {{- include "calendar-chart.calendar.labels" . | nindent 4 }}
  {{- with .Values.calendar.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.calendar.ingress.className }}
  ingressClassName: {{ .Values.calendar.ingress.className }}
  {{- end }}
  {{- if .Values.calendar.ingress.tls }}
  tls:
    {{- range .Values.calendar.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.calendar.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "calendar-chart.fullname" $ }}-calendar
                port:
                  number: {{ $.Values.calendar.service.port }}
          {{- end }}
    {{- end }}
{{- end }}

